services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sabine-website
    container_name: sabine-website
    restart: always
    ports:
      - "${PORT}:${PORT}"
    network_mode: host